Pose
ultralytics/yolo-ios-app pull request #56
Opened 2024-08-12 05:52 UTC by john-rocky

@ambitious-octopus 

I've added pose functionality to the app and committed to the pose branch.
This branch is based on the branch that 
added human and segmentation.
As always, please let me know if there are any issues that need to be resolved during the integration process (e.g. maintaining model references).

Thanks in advance.

![IMG_3582](https://github.com/user-attachments/assets/dd317e6d-b56c-4c08-9006-0f3f8d73f9f6)

2024-08-21 15:05 UTC, ambitious-octopus requested changes
Hey @john-rocky , could you please review this PR and remove any unnecessary elements? I’d like to ensure we’re focusing solely on items related to pose estimation. Thanks!

2024-08-21 16:00 UTC, john-rocky commented
Understood. I will modify the main branch to a simple code with pose function added. Please wait a moment.

2024-08-24 02:57 UTC, john-rocky commented
@ambitious-octopus 
I removed unnecessary elements. Currently, this branch only adds the pause function to the main branch.

2024-08-24 10:49 UTC, ambitious-octopus requested changes
Hey @john-rocky it seems that there are still some merge conflicts. Can you please resolve them?

2024-08-24 20:17 UTC, john-rocky commented
@ambitious-octopus
I fixed the conflicts.
I tested this branch. This works fine.

2025-01-25 12:38 UTC, closed without merging